image:
- Visual Studio 2015
#- Ubuntu

before_build:
- mkdir build && cd build && cmake ..

configuration:
  - Release

build:
  project: build\audio-processing-module.sln
  parallel: true
  #verbosity: quiet
